import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const timerSrc = await readFile(new URL("../src/sleepTimer.ts", import.meta.url), "utf8");
const app = await readFile(new URL("../src/App.tsx", import.meta.url), "utf8");
const css = await readFile(new URL("../src/styles.css", import.meta.url), "utf8");
const main = await readFile(new URL("../electron/main.cjs", import.meta.url), "utf8");
const api = await readFile(new URL("../src/api.ts", import.meta.url), "utf8");

assert.doesNotMatch(app, /Message Amadeus/);
assert.doesNotMatch(app, /Conversation/);
assert.doesNotMatch(app, /sendMessage/);
assert.doesNotMatch(app, /MahoPuppet/);
assert.doesNotMatch(app, /OVERLAY_CHARACTER/);
assert.match(app, /className="overlay"/);
assert.match(app, /Live2DCharacter/);
assert.match(app, /sendInteraction/);
const pointer = await readFile(new URL("../src/overlayPointer.ts", import.meta.url), "utf8");
const hits = await readFile(new URL("../src/interactions.ts", import.meta.url), "utf8");
assert.match(hits, /label: "Head Pat"/);
assert.match(hits, /label: "Special touch"/);
assert.doesNotMatch(hits, /label: "Cat"/);
assert.match(app, /ZzzLayer/);
assert.match(app, /useKurisuSleep/);
assert.match(timerSrc, /IDLE_SLEEP_MS = 45_000/);
assert.match(css, /\.overlay\s*\{/);
assert.match(css, /\.zzz-layer/);
assert.doesNotMatch(css, /\.chat-panel/);
assert.match(main, /transparent:\s*true/);
assert.match(main, /alwaysOnTop:\s*true/);
assert.match(main, /WINDOW_WIDTH = 520/);
assert.match(main, /WINDOW_HEIGHT = 720/);
assert.match(main, /setIgnoreMouseEvents/);
assert.match(main, /Amadeus Overlay/);
assert.match(main, /overlayMenuTemplate/);
assert.match(main, /en: "English"/);
assert.match(main, /ja: "Japanese"/);
assert.match(main, /Quit Amadeus Overlay/);
assert.match(main, /show-menu/);
assert.match(pointer, /contextmenu/);
assert.match(pointer, /showMenu/);
assert.match(api, /voice/);
assert.match(api, /"en" \| "ja"/);

const rootReadme = await readFile(new URL("../../README.md", import.meta.url), "utf8");
assert.match(rootReadme, /# amadeus-overlay/);
assert.match(rootReadme, /Add sleep to original Amadeus/);
assert.match(rootReadme, /kurisu-sleep\.patch/);
assert.match(rootReadme, /start_local\.bat/);
assert.match(rootReadme, /py -3\.12/);
assert.match(rootReadme, /martialsystems\/amadeus-overlay/);
assert.match(rootReadme, /English, Japanese, or Quit/);
assert.match(rootReadme, /level-matched/);
assert.match(rootReadme, /does not repeat/);
assert.match(rootReadme, /docs\/demo\.mp4/);
assert.match(
  rootReadme,
  /^https:\/\/github\.com\/user-attachments\/assets\/796cd394-dda2-4fa0-9cc7-15c19465914b$/m,
);
assert.doesNotMatch(rootReadme, /<video/);
const demo = await readFile(new URL("../../docs/demo.mp4", import.meta.url));
assert.ok(demo.byteLength > 100_000, String(demo.byteLength));
const demoHead = Buffer.from(demo.subarray(0, 80));
assert.ok(demoHead.includes(Buffer.from("ftyp")));
assert.doesNotMatch(demoHead.toString("latin1"), /git-lfs/);
assert.doesNotMatch(rootReadme, /sg-overlay/);
assert.doesNotMatch(rootReadme, /Maho sits/);

const winBat = await readFile(new URL("../../start_local.bat", import.meta.url), "utf8");
assert.match(winBat, /launcher\.py" --no-ai/);
assert.match(winBat, /backend\\\.venv\\Scripts\\python\.exe/);
assert.doesNotMatch(rootReadme, /^Does /m);
assert.doesNotMatch(rootReadme, /\u2014/);
assert.doesNotMatch(rootReadme, /What it is not/);
assert.match(rootReadme, /ko-fi\.com\/martialgames/);
assert.match(rootReadme, /Donate on Ko-fi/);

const license = await readFile(new URL("../../LICENSE", import.meta.url), "utf8");
const notice = await readFile(new URL("../../NOTICE", import.meta.url), "utf8");
const sleepGuide = await readFile(new URL("../../contrib/sleep-idle/README.md", import.meta.url), "utf8");
assert.match(license, /MIT License/);
assert.match(license, /Martial Systems LLC/);
assert.match(notice, /Live2D Cubism Core/);
assert.match(notice, /amadeus-overlay/);
assert.doesNotMatch(notice, /Maho stills/);
assert.match(sleepGuide, /reflectors02\/Amadeus-Project/);
assert.match(sleepGuide, /sleepTimer\.ts/);
assert.match(sleepGuide, /kurisu-sleep\.patch/);
assert.match(sleepGuide, /amadeus-overlay/);
assert.doesNotMatch(sleepGuide, /\u2014/);
